-- =============================================================================
-- Seed Data — Demo records for development and testing
-- Run AFTER schema.sql:
--   mysql -u root -p hostel_food_db < database/seeds/seed_data.sql
-- =============================================================================
-- Note: Password hashes must be generated by the backend (werkzeug).
--       Use backend/seed_data.py for accounts with working passwords.
-- =============================================================================

USE hostel_food_db;

-- Holidays (for ML is_holiday feature)
INSERT INTO holidays (holiday_date, holiday_name, description) VALUES
('2026-01-26', 'Republic Day', 'National holiday'),
('2026-08-15', 'Independence Day', 'National holiday'),
('2026-10-02', 'Gandhi Jayanti', 'National holiday')
ON DUPLICATE KEY UPDATE holiday_name = VALUES(holiday_name);

-- Announcements (no FK dependency on students)
INSERT INTO announcements (title, description, priority, expiry_date) VALUES
('Hostel Timings Update', 'Hostel gates close at 10:00 PM on weekdays and 11:00 PM on weekends.', 'high', DATE_ADD(CURDATE(), INTERVAL 30 DAY)),
('Mess Menu Survey', 'Please complete the food preference survey by this Friday.', 'medium', DATE_ADD(CURDATE(), INTERVAL 14 DAY)),
('Water Supply Maintenance', 'Water supply interruption on Sunday 8:00 AM – 12:00 PM.', 'low', DATE_ADD(CURDATE(), INTERVAL 7 DAY))
ON DUPLICATE KEY UPDATE title = VALUES(title);
